In [4]:
import numpy as np
import math

In [ ]:
class TicTacToe:
    def __init__(self):
        self.row_count = 3
        self.column_count = 3
        self.action_size = self.row_count * self.column_count
    
    def get_initial_state(self):
        return np.zeros((self.row_count, self.column_count))
    
    def get_next_state(self, state, action, player):
        row = action // self.column_count
        column = action % self.row_count
        state[row, column] = player
        return state
    
    def get_valid_moves(self, state):
        return (state.reshape(-1) == 0).astype(np.uint8)
    
    def check_win(self, state, action):
        if action == None:
            return False
        row = action // self.column_count
        column = action % self.column_count
        player = state[row, column]
        win = (
            np.sum(state[row, :]) == player * self.column_count
            or np.sum(state[:, column]) == player * self.row_count
            or np.sum(np.diag(state)) == player * self.row_count
            or np.sum(np.diag(np.flip(state, axis=1))) == player * self.row_count
        )
        return win


    def get_value_and_terminated(self, state, action) -> tuple:
        if self.check_win(state, action):
            return 1, True
        
        if np.sum(self.get_valid_moves(state)) == 0:
            return 0, True
        
        return 0, False
        

    def get_opponent(self, player):
        return -player
    
    def get_opponent_value(self, value):
        return -value
    
    
    


In [3]:
tictactoe = TicTacToe()
player = 1
state = tictactoe.get_initial_state()



while True:
    print(state)
    valid_moves = tictactoe.get_valid_moves(state)
    print("valid moves", [i for i in range(tictactoe.action_size) if valid_moves[i] == 1])
    action = int(input(f"{player}: "))

    if valid_moves[action] == 0:
        print("Action not valid")

        continue

    state = tictactoe.get_next_state(state, action, player)

    value, is_terminal = tictactoe.get_value_and_terminated(state, action)


    if is_terminal:
        print(state)
        if value == 1:
            print(f"{player} won")

        else:
            print("draw")
            break    
 
    player = tictactoe.get_opponent(player)
            




[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
valid moves [0, 1, 2, 3, 4, 5, 6, 7, 8]
[[0. 1. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
valid moves [0, 2, 3, 4, 5, 6, 7, 8]
[[-1.  1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
valid moves [2, 3, 4, 5, 6, 7, 8]
[[-1.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
valid moves [2, 4, 5, 6, 7, 8]
[[-1.  1. -1.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
valid moves [4, 5, 6, 7, 8]
[[-1.  1. -1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
valid moves [4, 5, 6, 7]
Action not valid
[[-1.  1. -1.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
valid moves [4, 5, 6, 7]
[[-1.  1. -1.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
valid moves [5, 6, 7]
[[-1.  1. -1.]
 [ 1. -1.  1.]
 [ 0.  0.  1.]]
valid moves [6, 7]
[[-1.  1. -1.]
 [ 1. -1.  1.]
 [-1.  0.  1.]]
-1 won
[[-1.  1. -1.]
 [ 1. -1.  1.]
 [-1.  0.  1.]]
valid moves [7]
[[-1.  1. -1.]
 [ 1. -1.  1.]
 [-1.  1.  1.]]
draw


In [ ]:
class Node:
    def __init__(self, game, args, state, parent=None, action_taken=None):
        self.game = game
        self.state = state
        self.parent = parent
        self.action_taken = action_taken

        self.children = []
        self.expandable_moves = game.get(valid_moves(state))
        self.visit_count = 0
        self.value_sum = 0

    def is_fully_expanded(self):
        return np.sum(self.expandable_moves) == 0 and len(self.children) > 0

    def select(self):
        best_child = None
        best_ucb = -np.inf

        for child in self.children:
            ucb = self.get_ucb(child)

            if ucb > best_ucb:
                best_child = child
                best_ucb = ucb

        return best_child
    
    def get_ucb(self, child):
        q_value = 1 - ((child.value_sum / child.visit_count) + 1) / 2
        return q_value + self.args['C'] * math.sqrt(math.log(self.visit_count) / child.visit_count)




class MCTS:
    def __init__(self, game, args):
        self.game = game
        self.args = args

    def search(self, state):
        root = Node(self.game, self.args, state)
         
        for search in range(self.args['num_searches']):
            # selection
            node = root
            # explansion
            while node.is_fully_expanded():
                node = node.select()

            value, is_terminal = self.game.get_value_and_terminated(node.state, node.action_taken)



            # simulation
            # backprop

        # return visit_counts